export const CREATE_TRANSACTION_REQUEST = 'CREATE_TRANSACTION_REQUEST';
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';
export const CREATE_TRANSACTION_FAIL = 'CREATE_TRANSACTION_FAIL';

export const GET_USER_TRANSACTIONS_REQUEST = 'GET_USER_TRANSACTIONS_REQUEST';
export const GET_USER_TRANSACTIONS_SUCCESS = 'GET_USER_TRANSACTIONS_SUCCESS';
export const GET_USER_TRANSACTIONS_FAIL = 'GET_USER_TRANSACTIONS_FAIL';

export const GET_TRANSACTION_DETAIL_REQUEST = 'GET_TRANSACTION_DETAIL_REQUEST';
export const GET_TRANSACTION_DETAIL_SUCCESS = 'GET_TRANSACTION_DETAIL_SUCCESS';
export const GET_TRANSACTION_DETAIL_FAIL = 'GET_TRANSACTION_DETAIL_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';